export const list = [
	{ value: 'BG', name: 'ブルガリア語' },
	{ value: 'CS', name: 'チェコ語' },
	{ value: 'DA', name: 'デンマーク語' },
	{ value: 'DE', name: 'ドイツ語' },
	{ value: 'EL', name: 'ギリシャ語' },
	{ value: 'EN-GB', name: '英語 (イギリス)' },
	{ value: 'EN-US', name: '英語 (アメリカ)' },
	{ value: 'ES', name: 'スペイン語' },
	{ value: 'ET', name: 'エストニア語' },
	{ value: 'FI', name: 'フィンランド語' },
	{ value: 'FR', name: 'フランス語' },
	{ value: 'HU', name: 'ハンガリー語' },
	{ value: 'ID', name: 'インドネシア語' },
	{ value: 'IT', name: 'イタリア語' },
	{ value: 'JA', name: '日本語' },
	{ value: 'KO', name: '韓国語' },
	{ value: 'LT', name: 'リトアニア語' },
	{ value: 'LV', name: 'ラトビア語' },
	{ value: 'NB', name: 'ノルウェー語 (ブークモール)' },
	{ value: 'NL', name: 'オランダ語' },
	{ value: 'PL', name: 'ポーランド語' },
	{ value: 'PT-BR', name: 'ポルトガル語 (ブラジル)' },
	{ value: 'PT-PT', name: 'ポルトガル語 (ブラジル以外)' },
	{ value: 'RO', name: 'ルーマニア語' },
	{ value: 'RU', name: 'ロシア語' },
	{ value: 'SK', name: 'スロバキア語' },
	{ value: 'SL', name: 'スロベニア語' },
	{ value: 'SV', name: 'スウェーデン語' },
	{ value: 'TR', name: 'トルコ語' },
	{ value: 'UK', name: 'ウクライナ語' },
	{ value: 'ZH', name: '中国語 (簡体字)' }
];
